# Generated by Django 2.2.6 on 2019-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_class',
            name='file_link',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
