# Generated by Django 2.2.6 on 2019-10-02 17:43

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchical_data', '0003_auto_20191002_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_class',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'is_folder': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hierarchical_data.File_Class'),
        ),
    ]
